local Macro = {
  Category = {
    Receive = 1,
    NewArrivals = 2,
    Other = 1000
  },
  UserLabel = {
    NewHandPlayer = 1,
    BackFlowPlayer = 2,
    RetainPlayer = 3
  },
  Login_Modules = {
    "client.slua.logic.reddot.reddot_message_center",
    "client.slua.logic.reddot.reddot_group",
    "client.slua.logic.reddot.data.CommunityReddotData",
    "client.slua.logic.supercore.supercore_reddot_data",
    "client.slua.logic.activity.RedPoint.ActivityRedDot",
    "client.slua.logic.lobby.lab.general_lab_reddot_data",
    "client.logic.season.red_point.season_redpoint_data",
    "client.slua.logic.match.red_point.match_redpoint_data",
    "client.logic.achievement.achievement_red",
    "client.slua.logic.corps.corps_reddot_data",
    "client.slua.logic.task.assembly_reddot_data",
    "client.slua.logic.task.level_task_reddot_data",
    "client.slua.logic.mail.logic_mail_redpoint_data",
    "client.slua.logic.ban_reddot.ban_reddot_data",
    "client.slua.logic.esport.esport_reddot_data",
    "client.slua.logic.career.logic_careerRedPoint",
    "client.slua.logic.vlink_sdk.vlink_reddot_data",
    "client.slua.logic.lbs.lbs_reddot_data",
    "client.slua.logic.lobby.logic_lobby_reddot",
    "client.slua.logic.mentor.mentor_reddot_data",
    "client.slua.logic.esport.center_reddot_data",
    "client.slua.logic.activity.newbie.logic_newbie_activity_reddot",
    "client.slua.logic.activity.newbie.logic_newbie_reward_abtest_reddot",
    "client.slua.logic.return_activity.logic_return_activity_redpoint_data",
    "client.slua.logic.home.Collection.home_collection_task_redpoint",
    "client.slua.logic.ugc.center.ugc_center_reddot_data",
    "client.slua.logic.ugc.mail.ugc_mail_reddot_data",
    "client.slua.logic.ugc.task.ugc_task_reddot_data",
    "client.slua.logic.ugc.playlevel.ugc_playlevel_reddot_data",
    "client.slua.logic.device_album.logic_device_album_interface",
    "client.slua.logic.ugc.photo.ugc_photo_reddot_data",
    "client.slua.umg.Kol_IN.kol_reddot_config",
    "client.slua.logic.ugc.WowPass.wowpass_task_reddot_data",
    "client.slua.logic.ugc.comment.ugc_comment_reddot_data",
    "client.slua.umg.setting.logic_setting_reddot_data"
  },
  TipsType = {MessageMainType = 1, RewardMainType = 2},
  SystemName = {
    Wardrobe = "wardrobe",
    Shop = "shop",
    RP = "RP",
    ActivityCenter = "ActivityCenter",
    ActivityCenterWOW = "ActivityCenterWOW",
    ActivityCenterPlanPH = "ActivityCenterPlanPH",
    ActivityCenterTxMission = "ActivityCenterTxMission",
    ActivityCenterSport = "ActivityCenterSport",
    Corps = "corps",
    ModeSelect = "modeselect",
    Achievement = "achievement",
    Ban = "ban",
    Mail = "mail",
    ComeBack = "comeback",
    ESport = "esport",
    Supply = "supply",
    Season = "season",
    Prime = "prime",
    Golden_Suit = "golden_suit",
    Weapon_DIY = "weapon_diy",
    Character = "character",
    Research = "research",
    Companions = "Companions",
    Vehicle = "Vehicle",
    Sponsor = "sponsor",
    EsportCenter = "esportcenter",
    Vlink = "vlink",
    community = "community",
    WarZone = "WarZone",
    Career = "Career",
    NewbieActivity = "NewbieActivity",
    NewbieRewardABTest = "NewbieRewardABTest",
    ReturnActivity = "ReturnActivity",
    SupplyM = "supply2",
    ShopJK = "shop2",
    SuperStar = "superstar",
    ThemeSystem = "ThemeSystem",
    ManorTask = "ManorTask",
    UGCCenter = "UGCCenter",
    UGCTask = "UGCTask",
    UGCWOWPlay = "UGCWOWPlay",
    UGCMail = "UGCMail",
    UGCSeason = "UGCSeason",
    UGCPhoto = "UGCPhoto",
    KolRank = "KolRank",
    MixItemDraw = "MixItemDraw",
    UGCWOWPassTask = "UGCWOWPassTask",
    UGCComment = "UGCComment",
    BlackFriday = "BlackFriday",
    NewUserFission = "NewUserFission",
    Setting = "Setting",
    GarageTheme = "GarageTheme",
    Assembly = "assembly",
    CardCollection = "CardCollection"
  }
}
return Macro