local StoreUtils = require("client.slua.logic.store.utils.store_utils_config")
require("client.slua.logic.store.utils.store_utils_avatar")
require("client.slua.logic.store.utils.store_utils_ban_box")
require("client.slua.logic.store.utils.store_utils_buy")
require("client.slua.logic.store.utils.store_utils_convert_info")
require("client.slua.logic.store.utils.store_utils_detail")
require("client.slua.logic.store.utils.store_utils_exchange")
require("client.slua.logic.store.utils.store_utils_gift")
require("client.slua.logic.store.utils.store_utils_hot")
require("client.slua.logic.store.utils.store_utils_item")
require("client.slua.logic.store.utils.store_utils_jump")
require("client.slua.logic.store.utils.store_utils_money")
require("client.slua.logic.store.utils.store_utils_other")
require("client.slua.logic.store.utils.store_utils_page")
require("client.slua.logic.store.utils.store_utils_pet")
require("client.slua.logic.store.utils.store_utils_region")
require("client.slua.logic.store.utils.store_utils_supply")
require("client.slua.logic.store.utils.store_utils_tab")
return StoreUtils